dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev

feature_gates:
  component.UseLocalHostAsDefaultHost: true
exporters:
  - gomod:
      # NOTE: Prior to v0.86.0 use the `loggingexporter` instead of `debugexporter`.
      go.opentelemetry.io/collector/exporter/debugexporter v0.113.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.113.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudexporter v0.113.0 
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudpubsubexporter v0.113.0
processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.113.0
  - gomod:
    #github.com/apresti12/splitattributesprocessor v0.0.1
      ./splitAttributesProcessor
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/cumulativetodeltaprocessor v0.113.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.113.0
  - gomod:
      go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.113.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.113.0
receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.113.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0

extensions:
  - gomod: 
      go.opentelemetry.io/collector/extension/memorylimiterextension v0.113.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.113.0
